services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale-subnet-router
    hostname: nebuchadnezzar-subnet-router
    network_mode: host
    environment:
      - TS_AUTHKEY=tskey-auth-kFrMm8tFDE11CNTRL-gpFemBa2Hh4oCcV1tW1hg4dsV1eZb5Yi
      - TS_EXTRA_ARGS=--advertise-exit-node --advertise-routes=192.168.3.0/24 --accept-dns=false
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - /lib/modules:/lib/modules:ro
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
